### ISSUE TITLE
Site shows and updates, but CSS not rendering

### ISSUE THREAD

**Issue by lisawilliams** [lisawilliams/lisa#1]
Possibly useful: https://github.com/jekyll/jekyll-help/issues/281

**Comment by lisawilliams** [comment]
Changing baseurl setting fixes problem with CSS not rendering. Baseurl tells Jekyll/gh-pages what the relative path is to files around index.html.

**Comment by inwardmovement** [comment]
Thanks, that fixed my issue too. I've been searching in Jekyll's issues but can't figure out why they don't prefill the baseurl with the blog's name...

**Comment by lisawilliams** [comment]
My pleasure!
